if(EXISTS "C:/Users/maxaf/Documents/DSA/DSA-Project1-AVLTree/Tests-b12d07c_tests.cmake")
  include("C:/Users/maxaf/Documents/DSA/DSA-Project1-AVLTree/Tests-b12d07c_tests.cmake")
else()
  add_test(Tests_NOT_BUILT-b12d07c Tests_NOT_BUILT-b12d07c)
endif()
